import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Referr Farm | Let's get started",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <footer>Join us today</footer>
    </>
  );
}
